apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    project: roboshop
    component: mongodb
    tier: db
spec:
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  clusterIP: None
  labels:
    project: roboshop
    component: mongodb
    tier: db
spec:
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    component: mongodb
    tier: db
spec:
  replicas: 2
  serviceName: mongodb-headless
  slector:
    matchLabels: 
      project: roboshop
      component: mongodb
      tier: db
  template:
    metadata:
      labels:
        project: roboshop
        component: mongodb
        tier: db
    spec:
      containers:
      - name: mongodb
        images: shanmukhatadisetti/mongodb:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 27017
        readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 30
          periodSeconds: 20
        livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 30
          periodSeconds: 20
        volumeMounts:
        - name: mongodb-pvc
          mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongodb-pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "roboshop-ebs"
        resources:
          requests:
            storage: 5Gi


    
